"""add change request model

Revision ID: f95087bc4836
Revises: 3ed7277ca67e
Create Date: 2022-08-17 12:51:04.290549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f95087bc4836'
down_revision = '3ed7277ca67e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_request',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_change_request_number'), 'change_request', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_request_number'), table_name='change_request')
    op.drop_table('change_request')
    # ### end Alembic commands ###
